# Generated by Django 4.2.1 on 2023-05-03 18:57

import baham.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voided', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField()),
                ('date_voided', models.DateField()),
                ('created_by', models.CharField(editable=False, max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('voided_by', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('type', models.CharField(choices=[('COMPANION', 'Companion'), ('OWNER', 'Owner')], max_length=10)),
                ('primary_contacts', models.CharField(max_length=20)),
                ('alternate_contacts', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=255)),
                ('address_latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('address_longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('landmark', models.CharField(max_length=255)),
                ('town', models.CharField(choices=[('Malir', 'Malir'), ('North Nazimabad', 'North Nazimabad'), ('Gadap', 'Gadap'), ('Gulberg', 'Gulberg'), ('Liaquatabad', 'Liaquatabad'), ('Gulshan-e-Iqbal', 'Gulshan-e-Iqbal'), ('Jamshed', 'Jamshed'), ('Kemari', 'Kemari'), ('Korangi', 'Korangi'), ('Landhi', 'Landhi'), ('New karachi', 'New karachi'), ('Bin Qasim', 'Bin Qasim'), ('Orangi', 'Orangi'), ('SITE', 'SITE'), ('Saddar', 'Saddar'), ('Shah Faisal', 'Shah Faisal')], max_length=50)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('date_deactivated', models.DateTimeField(editable=False, null=True)),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('voided', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField()),
                ('date_voided', models.DateField()),
                ('created_by', models.CharField(editable=False, max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('voided_by', models.CharField(max_length=50)),
                ('model_id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=20)),
                ('model', models.CharField(default='Unknown', max_length=50)),
                ('type', models.CharField(choices=[('AUTO_RICKSHAW', 'Auto Rickshaw'), ('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatch Back'), ('SUV', 'Sub-Urban Vehicle'), ('VAN', 'Van'), ('HIGH_ROOF', 'High Roof'), ('MOTORCYCLE', 'Moto Cycle/Scooter')], help_text='Select the vehicle chassis type', max_length=50)),
                ('capacity', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'db_table': 'baham_vehicle_model',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('voided', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField()),
                ('date_voided', models.DateField()),
                ('created_by', models.CharField(editable=False, max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('voided_by', models.CharField(max_length=50)),
                ('vehicle_id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(help_text='Unique registration/license plate no. of the vehicle.', max_length=10, unique=True)),
                ('color', models.CharField(default='white', max_length=50, validators=[baham.models.validate_colors])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('FULL', 'Full'), ('INACTIVE', 'Inactive'), ('REMOVED', 'Removed')], max_length=50)),
                ('picture1', models.ImageField(null=True, upload_to='pictures')),
                ('picture2', models.ImageField(null=True, upload_to='pictures')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.vehiclemodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('voided', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('date_updated', models.DateField()),
                ('date_voided', models.DateField()),
                ('created_by', models.CharField(editable=False, max_length=50)),
                ('updated_by', models.CharField(max_length=50)),
                ('voided_by', models.CharField(max_length=50)),
                ('contract_id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('fuel_share', models.PositiveSmallIntegerField(help_text='Percentage of fuel cost')),
                ('maintenance_share', models.PositiveSmallIntegerField(help_text='Percentage of maintenance share')),
                ('schedule', models.CharField(max_length=255)),
                ('companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.userprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baham.vehicle')),
            ],
        ),
    ]
